name: Erlang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: ["erlang:25", "erlang:26"]

    container:
      image: ${{ matrix.otp }}

    steps:
    - uses: actions/checkout@v2
    - name: Install latest g++
      run: |
        # ls -l /usr/bin/g++*
        update-alternatives --install /usr/bin/g++ g++ /usr/bin/gcc-10 100
        g++ --version
        git config --global user.name "Test User"
        git config --global user.email "test@gmail.com"
    - name: Install libgit2
      run: |
        apt-get update -y && apt-get install -y libgit2-dev
    - name: Compile
      run:  make
    - name: Run tests
      run:  make test
