name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:26

    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout all history for all branches and tags
        fetch-depth: 0
    - name: Compile
      run:  make
    - name: Run tests
      run:  make test
